### ISSUE TITLE
Issue: Environment Variables Only Retain One Line

### ISSUE THREAD

**Issue by antowaddle** [dpanshug/cypress-test-explorer#30]
Steps to replicate:
- Add a multi-line env. variable
- Click Save
- Navigate away from the plugin to Source Control/Extensions etc.

Actual result:
- Data is removed

Expected result:
- All entered data should be saved

![image](https://github.com/user-attachments/assets/6cc73952-4aca-498d-b80d-253bc8960a56)

After clicking Save and navigating away from the Add on
![image](https://github.com/user-attachments/assets/e6e270ec-f63c-4cf0-b4fb-928c2566cd70)

**Comment by dpanshug** [comment]
To avoid confusion between run environment variables and other environment variables, this section has been renamed to Cypress Run Variables.

Users can only enter key-value pairs, and validation has been added to enforce this. Any entries that do not follow this format will be ignored.

@antowaddle  To make this extension compatible with other environment variables, we will explore how to open the run in a terminal where the user has entered the variables manually.
